global_config:
  prefix: DOMWALL_
  log_level: DEBUG
ip_groups:
  - location: DFW01
    group_name: googley
    domain_names:
      - www.google.com
      - google.com
      - mail.google.com
  - location: DFW01
    group_name: armory
    domain_names:
      - armor.com
      - www.armor.com
      - docs.armor.com
